name: servicenow-change-plugin
rundeckPluginVersion: 2.0
author: André Müzel Brisolla
description: This plugin provides a method abstracting to create and close a Service Now change.
rundeckCompatibilityVersion: 3.x
targetHostCompatibility: unix
license: Apache 2.0
tags:
    - script
    - WorkflowNodeStep
date: 2023-06-12T17:29:26.695694061Z
version: 0.4.0
providers:
    - name: servicenow-change-plugin
      service: WorkflowNodeStep
      title: servicenow-change-plugin
      description: Create a Service Now Change and wait form approval.
      plugin-type: script
      script-interpreter: /usr/bin/python3 -u
      script-file: exec.py
      script-args: -s ${config.servicenow_server} -u ${config.servicenow_username} -p ${config.servicenow_password} -a ${config.servicenow_action} -r ${config.rundeck_server} -k ${config.rundeck_token}
      config:
        - type: String
          name: servicenow_username
          title: servicenow_username
          description: Username to access ServiceNow
        - type: String
          name: servicenow_password
          title: servicenow_password
          description: Key path to access ServiceNow storage password
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
        - type: String
          name: servicenow_server
          title: servicenow_server
          description: URL to access ServiceNow API
        - type: String
          name: servicenow_action
          title: servicenow_action
          description: Action to perform on Service Now (open_change, close_change)
          values: open_change, close_change
          default: open_change
        - type: String
          name: rundeck_server
          title: rundeck_server
          description: URL to access Rundeck API
        - type: String
          name: rundeck_token
          title: rundeck_token
          description: Key path to access Rundeck TOKEN storage password
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
