name: servicenow-approval-plugin
rundeckPluginVersion: 2.0
author: Rundeck Dev
description: Describe your plugin here
rundeckCompatibilityVersion: 3.x
targetHostCompatibility: unix
license: Apache 2.0
tags:
    - script
    - WorkflowNodeStep
date: 2023-06-12T17:29:26.695694061Z
version: 1.0.0
providers:
    - name: servicenow-approval-plugin
      service: WorkflowNodeStep
      title: servicenow-approval-plugin
      description: The description of servicenow-approval-plugin plugin
      plugin-type: script
      script-interpreter: /usr/bin/python3 -u
      script-file: exec.py
      script-args: -t rundeck-job-vmcreate -s ${config.servicenow_server} -u ${config.servicenow_username} -p ${config.servicenow_password} -a ${config.servicenow_action} -r ${config.rundeck_server} -k ${config.rundeck_token}
      config:
        - type: String
          name: servicenow_username
          title: ServiceNow username
          description: Key path to access to ServiceNow storage username
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
        - type: String
          name: servicenow_password
          title: ServiceNow username password
          description: Key path to access to ServiceNow storage password
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
        - type: String
          name: servicenow_server
          title: ServiceNow server
          description: Key path to access to ServiceNow server
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
        - type: String
          name: servicenow_action
          title: ServiceNow action
          description: Action to perform on Service Now (open_change, close_change)
          values: open_change, close_change
          default: open_change
        - type: String
          name: rundeck_server
          title: Rundeck server
          description: Rundeck server
        - type: String
          name: rundeck_token
          title: Rundeck api TOKEN
          description: Rundeck api TOKEN        