on: push
name: Build plugin ZIP package
jobs:
  build_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: build package
        run: make clean build

      - name: teste
        run: ls -lR